#!bin/bash

# Copyright (c) 2020 CodeBreaker.com.br
#
# Este script visa configurar o VirtualHost no Apache

# >> Variaveis <<
nomeVirtualHost=$1
pastaWWW="/var/www"
VIRTUALHOST=$pastaWWW/$nomeVirtualHost

pastaPublic=$VIRTUALHOST/public_html
pastaModulo=$pastaPublic/modulo

pastaAPACHE=/etc/httpd
pastaAvailable=$pastaAPACHE/sites-available
pastaEnabled=$pastaAPACHE/sites-enabled

arquivoConfigAPACHE=$pastaAPACHE/conf/httpd.conf
arquivoConfigVIRTUALHOST=$pastaAvailable/$nomeVirtualHost.conf

addConfigAPACHE="IncludeOptional sites-enabled/*.conf"

URL=$2

# >> Criando os diretórios
mkdir $VIRTUALHOST
mkdir $pastaPublic
mkdir $pastaModulo
mkdir $pastaAvailable
mkdir $pastaEnabled

# >> adicionando as pastas ao grupo de usuario Apache <<
chown -R apache:apache "$pastaPublic"
chown -R apache:apache "$pastaModulo"
chown -R apache:apache "$pastaAvailable"
chown -R apache:apache "$pastaEnabled"
chmod -R 755 $pastaWWW
chmod -R 755 $pastaPublic
chmod -R 755 $pastaModulo


# >> criar cópia de segurança do arquivo de configuração do apache <<
cp $arquivoConfigAPACHE $pastaAPACHE/httpd.conf_old

# >> adicionar comando no arquivo de configuração do apache <<
echo $addConfigAPACHE >> $arquivoConfigAPACHE

# >> Criando o arquivo de configuração do VirtualHost <<
echo "<VirtualHost *:80>
ServerName www.$URL
ServerAlias $URL
DocumentRoot $pastaPublic
<Directory $pastaModulo >
AllowOverride All
</Directory>
</VirtualHost>

<VirtualHost *:443>
DocumentRoot $pastaPublic
ServerName $URL:443
ServerAlias www.$URL:443
</VirtualHost>" > $arquivoConfigVIRTUALHOST


# Criar link simbolico do arquivo de configuração do VirtualHost <<
ln -s $pastaAvailable/$nomeVirtualHost.conf $pastaEnabled/$nomeVirtualHost.conf
ls -lah $pastaEnabled/$nomeVirtualHost.conf

# >> reiniciar serviço do apache <<
systemctl stop httpd.service
systemctl start httpd.service
systemctl restart httpd.service

